services:
    node:
        build: "./node"
        container_name: node
        hostname: node
        ports:
            - "8080:8080"
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        depends_on:
            couchdb:
                condition: service_healthy
        links:
            - couchdb
        networks:
            - frontend
            - backend
        env_file:
            - ${DOTFILES}/.env
        volumes:
            - ./node/public:/usr/src/app/public
            - ./node/config:/usr/src/app/config
            - ./node/models:/usr/src/app/models
            - ./node/routes:/usr/src/app/routes
            - ./node/views:/usr/src/app/views
            - ./node/server.js:/usr/src/app/server.js
    mail:
        build: "./mail"
        container_name: mail
        hostname: mail
        ports:
            - "465:465"
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        depends_on:
            - node
        links:
            - node
        networks:
            - backend
        env_file:
            - ${DOTFILES}/.env
        volumes:
            - ./mail/server.js:/usr/src/app/server.js
    api:
        build: "./api"
        container_name: api
        hostname: api
        ports:
            - '1515:1515'
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        depends_on:
            - node
            - ws
        links:
            - node
            - ws
        networks:
            - backend
        env_file:
            - ${DOTFILES}/.env
        volumes:
            - ./api/server.js:/usr/src/app/server.js
    ws:
        build: "./ws"
        container_name: ws
        hostname: ws
        ports:
            - '1337:1337'
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        depends_on:
            - node
        links:
            - node
        networks:
            - backend
        env_file:
            - ${DOTFILES}/.env
        volumes:
            - ./ws/server.js:/usr/src/app/server.js
    nginx:
        build: "./nginx"
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped
        depends_on:
            - node
        networks:
            - frontend
            - backend
        env_file:
            - ${DOTFILES}/.env
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/ssl:/etc/nginx/ssl
            - ${DOTFILES}/nginx/ssl/travelup_key.pem:/etc/nginx/ssl/travelup_key.pem
    couchdb:
        image: couchdb
        restart: always
        container_name: couchdb
        hostname: couchdb
        ports:
            - "5984:5984"
            - "6984:6984" # Management diretto (write) su https://localhost:6984/_utils/ e management cache (read) su https://localhost:4984/_utils/
        networks:
            - backend
        env_file:
            - ${DOTFILES}/.env
        volumes:
            - ./couchdb:/opt/couchdb/data
            - ./couchdb/local.ini:/opt/couchdb/etc/local.ini
            - ./nginx/ssl:/opt/couchdb/ssl
        healthcheck:
            test: [ "CMD-SHELL", "curl -f http://localhost:5984/" ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 40s
networks:
    frontend:
    backend:
