version: "3.8"
services:
    node:
        build:
          context: ./node
        container_name: node
        hostname: node
        ports:
            - "8080:8080"
        networks:
            - net
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - node
        networks:
            - net
networks:
    net:
        external: true
