name: "Docker Compose & Node"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install node (locally)
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies (locally)
      run: |
        npm ci --only=production --prefix ./main
        npm ci --only=production --prefix ./ws
        npm ci --only=production --prefix ./mail
        npm ci --only=production --prefix ./api
      
    - name: Start containers in testing environment and perform tests
      run: ./start test

    - name: Stop containers and clean leftovers
      if: always()
      run: ./clean
